## 线性回归介绍
- 线性回归是机器学习算法当中最基础的一个算法，是一个线性模型（不能挖掘数据之间的非线性关系）。
- 输入是多个变量，输出一个实数值，范围是整个实数空间即[-∞, +∞]
- 一般用于解决回归问题

## 数学表达式
假设数据输入是一个向量$x=[x_1, x_2, x_3, x_4, x_5,...., x_n]$，输出是一个实数值$y$，其数学表达式如下所示:
$$
y = xw^T+b
$$
- $x$是1行n列的矩阵，即数据的输入$x$
- $w$是线性回归模型的参数，是一个1行n列的矩阵，$T$表示矩阵的转置
- $b$是一个实数，表示线性回归的偏置项

## 线性回归的优点
- 建模速度快，因为不需要很复杂的计算（不需要进行指数运算什么之类的）
- 模型自带解释，从参数$w$可以看除哪个变量对最终结果的影响最大

## 线性回归的缺点
- 不能挖掘数据的非线性关系,对于非线性相关的数据来说模型过于简单以至于不能得到很好的结果
- 需要假设数据不存在非线性的关系，建模之前需要严格的假设
- 对变量的异常值非常敏感

## 一个小demo
给出一个函数，然后给数据的输出加上一个噪音，构成一个数据训练集

假设目标的函数是：
$$
y = 3x_1+5.6x_2+9.4x_3+10.4x_5+0.444
$$
## 训练过程
我们的目标就是得到$x_1$、$x_2$、$x_3$、$x_4$、$x_5$、$b$(0.444就是b)这几个参数

1. 随机初始化上述几个参数的数值
2. 损失函数使用mse
3. 使用梯度下降算法来进行参数的更新

In [1]:
import  torch
import random
import torch.nn.functional as F


# 目标参数
target_param = torch.tensor([3, 5.6, 9.4, 10.4])
target_param = target_param.view(4, 1)
target_bias = 0.444

def target_f(x):
    '''
    x是一个向量，即 5 个特征的值
    return number
    '''
    return x.mm(target_param) + target_bias


def get_batch_data(batch_size=32):
    # 让x的范围大一点
    x = torch.rand(batch_size,4)*random.randint(0, 100)
    y = target_f(x)
    return x, y+random.random()*2

# 初始化线性模型参数
train_param = torch.ones(4, 1, requires_grad=True)
train_bias = torch.rand(1, requires_grad=True)

batch_size = 66
epoch = 100
lr = 0.0001
# 训练1000次
for i in range(0, epoch+1):
    x, y = get_batch_data(batch_size)
    out = x.mm(train_param)+train_bias
    loss = F.mse_loss(y, out)
    loss.backward()
    with torch.no_grad():
        train_param -= lr*train_param.grad
        train_bias -= lr*train_bias
        train_param.grad.zero_()
        train_bias.grad.zero_()
    if i % 10 == 0:
        print(target_param.detach().numpy().reshape(-1), target_bias)
        print(train_param.detach().numpy().reshape(-1), train_bias.item())
        print('-'*24)

[ 3.   5.6  9.4 10.4] 0.444
[1.8529184 1.9021056 1.9214013 2.003685 ] 0.24211327731609344
------------------------
[ 3.   5.6  9.4 10.4] 0.444
[5.492904 6.655674 8.159406 9.20212 ] 0.24187128245830536
------------------------
[ 3.   5.6  9.4 10.4] 0.444
[4.2492027 5.9966645 8.410351  9.463966 ] 0.24162951111793518
------------------------
[ 3.   5.6  9.4 10.4] 0.444
[3.6671007 5.818971  8.9215355 9.995118 ] 0.2413879930973053
------------------------
[ 3.   5.6  9.4 10.4] 0.444
[ 3.3860586  5.7363944  9.129061  10.168412 ] 0.24114671349525452
------------------------
[ 3.   5.6  9.4 10.4] 0.444
[ 3.206347  5.687012  9.257879 10.298907] 0.24090568721294403
------------------------
[ 3.   5.6  9.4 10.4] 0.444
[ 3.105652   5.6471004  9.344035  10.355228 ] 0.24066488444805145
------------------------
[ 3.   5.6  9.4 10.4] 0.444
[ 3.041664   5.6167226  9.3728285 10.375135 ] 0.24042432010173798
------------------------
[ 3.   5.6  9.4 10.4] 0.444
[ 3.0177956  5.604609   9.376344  10.3784   ]